export default[
    {
        id:1,
        name:'Programming',
        icon:'/coding.svg',
        prompt:''
    },
    {
        id:2,
        name:'Health',
        icon:'/health.svg',
        prompt:''
    },
    {
        id:3,
        name:'Creativity',
        icon:'/creative.svg',
        prompt:''
    },
    {
        id:4,
        name:'Academics',
        icon:'/books.svg',
        prompt:''
    },
    {
        id:5,
        name:'Finance',
        icon:'/finance.svg',
        prompt:''
    },
    {
        id:6,
        name:'Science',
        icon:'/science.svg',
        prompt:''
    }
]